// Generated by CoffeeScript 1.7.1
(function() {
  var async, chunk, end, fs, start, sys, tmp_file, _i, _results;

  sys = require('async');

  fs = require('fs');

  async = require('async');

  process.on('message', function(message) {
    return console.log("recieve message");
  });

  chunk = (function() {
    _results = [];
    for (_i = 1; _i < 300000; _i++){ _results.push(_i); }
    return _results;
  }).apply(this);

  tmp_file = '/var/tmp/aa.txt';

  start = 0;

  end = 0;

  fs.open(tmp_file, 'w', function(err, fd) {
    start = (new Date()).getTime();
    console.log("start");
    return async.eachSeries(chunk, function(data, callback) {
      var head;
      head = new Buffer("this is line\n");
      return fs.write(fd, head, 0, head.length, null, function(err) {
        return callback();
      });
    }, function(err) {
      return fs.close(fd, function(close_err) {
        end = (new Date()).getTime();
        return console.log("done: " + (end - start));
      });
    });
  });

}).call(this);
