// Generated by CoffeeScript 1.7.1
(function() {
  var args, script, sup, supervisor;

  supervisor = require('../lib/supervisor');

  script = "./child.js";

  args = null;

  sup = supervisor.Supervisor(script, args, 1000);

  sup.run(function(err) {
    return console.log(err);
  });

}).call(this);
