#!/bin/bash

set -e

add-init(){
	if [ -x "/etc/init.d/uc-agent" ]; then
	  update-rc.d uc-agent defaults >/dev/null 2>&1
	fi
}

startup_program(){
    ## make sure /var/uc-agent directory was created
    if [ -f "/var/uc-agent" ]; then
        rm -rf /var/ucagent
    fi
    mkdir -p /var/uc-agent
    # migrate legacy run data to new location
    if [ -f "/var/run/uc-agent/license_key" ] && [ ! -f "/var/uc-agent/license_key" ]; then
        mv /var/run/uc-agent/license_key /var/uc-agent/license_key
    fi
    if [ -f "/var/run/uc-agent/agent_id" ] && [ ! -f "/var/uc-agent/agent_id" ]; then
        mv /var/run/uc-agent/agent_id /var/uc-agent/agent_id
    fi
    if [ -f "/var/run/uc-agent/posdb" ]; then
        rm -rf /var/run/uc-agent/posdb
    fi
    if [ -f "/var/uc-agent/license_key" ]; then
      echo "restart uc-agent ..."
      /etc/init.d/uc-agent restart
    fi
}


case "$1" in
    configure)
        add-init
        startup_program
        ;;
    abort-upgrade|abort-deconfigure|abort-remove)
        :
        ;;
    *)
        echo "Called with unknown argument $1, bailing out."
        exit 1
        ;;
esac