#!/bin/bash
#
# /etc/rc.d/init.d/ma-agent
#
# chkconfig: 345 80 20
# description: ma-agent
# processname: ma-agent
# pidfile: /var/run/ma-agent.pid
#
### BEGIN INIT INFO
# Provides:          ma-agent
# Default-Stop:      0 1 6
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Short-Description: ma-agent's init script
# Description:       ma-agent is a data collector
### END INIT INFO

# Source function library.
. /etc/init.d/functions

name="ma-agent"
prog="ma-agent"
ma_agent=/opt/ma-agent/bin/ma-agent

# timeout can be overridden from /etc/sysconfig/td-agent
STOPTIMEOUT=60

PIDFILE=${PIDFILE-/var/run/$prog.pid}
MA_AGENT_ARGS="${MA_AGENT_ARGS-start -s}"

RETVAL=0

start() {
	# Set Max number of file descriptors for the safety sake
	# see http://docs.fluentd.org/en/articles/before-install
	echo -n "Starting $name: "
	MA_AGENT_PID=$PIDFILE
	daemon --pidfile=$PIDFILE $ma_agent "$MA_AGENT_ARGS"
	RETVAL=$?
	echo
	if [[ ! "$RETVAL" -eq 0 ]]; then
		echo "please see more detail information in /var/log/ma-agent.log"
	fi
	return $RETVAL
}

stop() {
	echo -n "Shutting down $name: "
	$ma_agent stop
	RETVAL=$?
	 [ "$RETVAL" -eq 0 ] && success $"startup" || failure $"startup"
	 echo
	if [[ ! "$RETVAL" -eq 0 ]]; then
		echo "please see more detail information in /var/log/ma-agent.log"
	fi
	return $RETVAL
}

restart() {
	stop
	start
}



case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    reload)
	reload
	;;
    condrestart)
	[ -f /var/lock/subsys/$prog ] && restart || :
	;;
    configtest)
        configtest
        ;;
    status)
	status -p $PIDFILE 'td-agent'
	;;
    *)
	echo "Usage: $prog {start|stop|restart|status}"
	exit 1
	;;
esac
exit $?
